window:
  dimensions:
    columns: 120
    lines: 30
  opacity: 0.8
  # Values for `startup_mode`:
  #   - Windowed
  #   - Maximized
  #   - Fullscreen
  #startup_mode: Windowed

font:
  normal:
    family: InconsolataLGC Nerd Font Mono
  size: 16.0
  offset:
    x: 0
    y: 1

draw_bold_text_with_bright_colors: true

schemes:
  # Dracula theme for Alacritty
  # https://draculatheme.com/alacritty
  # Color palette
  # https://spec.draculatheme.com
  Dracula: &Dracula
    primary:
      background: '#282a36'
      foreground: '#f8f8f2'
      bright_foreground: '#ffffff'
    cursor:
      text: CellBackground
      cursor: CellForeground
    vi_mode_cursor:
      text: CellBackground
      cursor: CellForeground
    search:
      matches:
        foreground: '#44475a'
        background: '#50fa7b'
      focused_match:
        foreground: '#44475a'
        background: '#ffb86c'
      bar:
        background: '#282a36'
        foreground: '#f8f8f2'
    hints:
      start:
        foreground: '#282a36'
        background: '#f1fa8c'
      end:
        foreground: '#f1fa8c'
        background: '#282a36'
    line_indicator:
      foreground: None
      background: None
    selection:
      text: CellForeground
      background: '#44475a'
    normal:
      black: '#21222c'
      red: '#ff5555'
      green: '#50fa7b'
      yellow: '#f1fa8c'
      blue: '#bd93f9'
      magenta: '#ff79c6'
      cyan: '#8be9fd'
      white: '#f8f8f2'
    bright:
      black: '#6272a4'
      red: '#ff6e6e'
      green: '#69ff94'
      yellow: '#ffffa5'
      blue: '#d6acff'
      magenta: '#ff92df'
      cyan: '#a4ffff'
      white: '#ffffff'

colors: *Dracula

scrolling:
  history: 5000

selection:
  save_to_clipboard: true

cursor:
  style:
    shape: Beam
    blinking: On

mouse_bindings:
  - { mouse: Right, action: Paste }

key_bindings:
  # (Windows, Linux, and BSD only)
  - { key: F11, mods: None, action: ToggleFullscreen }
  - { key: L, mods: Control, action: ClearLogNotice }
  - { key: L, mods: Shift|Control, action: ClearHistory }
  - { key: L, mods: Control, chars: "\x0c" }
  - { key: T, mods: Shift|Control, action: SpawnNewInstance }
  - { key: PageUp, mods: None, action: ScrollPageUp, mode: ~Alt }
  - { key: PageDown, mods: None, action: ScrollPageDown, mode: ~Alt }
  - { key: Home, mods: Shift, action: ScrollToTop, mode: ~Alt }
  - { key: End, mods: Shift, action: ScrollToBottom, mode: ~Alt }
